### ISSUE TITLE
🐛 Fix modified date for notes when hosted

### ISSUE THREAD

**Issue by mrmartineau** [mrmartineau/gatsby-theme-code-notes#11]
The date for each note is based on when the file was modified, not by using frontmatter data. This modified date works fine when working locally but is broken when hosted.

**Comment by mrmartineau** [comment]
I have note been able to solve this yet. this link may give some help though: https://github.com/vercel/vercel/discussions/4101

**Comment by AlexEyler** [comment]
@mrmartineau is this the issue that you're referencing?

`6:10:31 PM: error There was an error in your GraphQL query:
6:10:31 PM: Cannot query field "fields" on type "Mdx".
6:10:31 PM: If you don't expect "fields" to exist on the type "Mdx" it is most likely a typo.
However, if you expect "fields" to exist there are a couple of solutions to common problems:
6:10:31 PM: - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
6:10:31 PM: - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
6:10:31 PM: - You want to optionally use your field "fields" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
6:10:31 PM: It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Mdx":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions`

I'm seeing this issue only in Netlify, not local :(
