### ISSUE TITLE
Error: [useColorMode] requires the ColorModeProvider component

### ISSUE THREAD

**Issue by aleksandar-todorovic** [mrmartineau/gatsby-theme-code-notes#14]
New to Gatsby, so I might be missing something obvious. Steps I've taken:

```bash
sudo npm install -g gatsby-cli
mkdir kb && cd kb
gatsby new . https://github.com/MrMartineau/gatsby-starter-code-notes
gastby develop
```

I chose to use npm as a package manager when asked by running `gatsby new`.

Result:

```
useColorMode
src/index.js:89

  86 | const { colorMode, setColorMode } = useThemeUI()
  87 | 
  88 | if (typeof setColorMode !== 'function') {
> 89 |   throw new Error(`[useColorMode] requires the ColorModeProvider component`)
  90 | }
  91 | 
  92 | return [colorMode, setColorMode]
```

**Comment by mrmartineau** [comment]
Hey @aleksandar-todorovic, thanks for raising this issue. I have not seen that bug (probably because I use yarn instead of mom  ntthese days), but I will look into it. 

It is strange that this error would be shown though because I am fairly certain gatsby-plugin-theme-ui should inject the provider that is needed. 

Thanks for trying my theme out, if you’re still stuck you can clone this repo to start your own code notes project.

**Comment by mrmartineau** [comment]
Hi @aleksandar-todorovic, I cannot reproduce your bug. Can you run `gatsby info --clipboard` in your project directory and paste the output here? Cheers

**Comment by EmilMarian** [comment]
I've managed to reproduce the issue.
I'm on Windows 10 btw.
@mrmartineau , let me know what other details you might need to debug this. I'm not a really fan of node and this is the first time I've installed Gatsby on my machine.

**Comment by mrmartineau** [comment]
@EmilMarian Could you run `gatsby info —clipboard` and paste the output?

**Comment by mrmartineau** [comment]
Just seen a related issue in the Theme UI repo: https://github.com/system-ui/theme-ui/issues/971 and it looks like it has been fixed here: https://github.com/gatsbyjs/gatsby/pull/24810. I don't think it has been released by Gatsby yet, but I'm sure it will soon. I will update the Gatsby dependency as soon as I see a new version
