### ISSUE TITLE
Not specifying front matter in at least one file causes GraphQL error

### ISSUE THREAD

**Issue by IronicBadger** [mrmartineau/gatsby-theme-code-notes#15]
The example front matter is:

```
---
title: Note frontmatter
emoji: 😃
tags:
  - metadata
link: https://zander.wtf
---
```

And so long as *at least one* note in the directory structure has an emoji or tags or link specified then the site builds just fine. But I'm not super keen on emoji in this use case so I deleted it from all my notes and the site fails to build. Error below:

```
There was an error in your GraphQL query:

Cannot query field "emoji" on type "MdxFrontmatter".

If you don't expect "emoji" to exist on the type "MdxFrontmatter" it is most likely a typo.
However, if you expect "emoji" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "emoji" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "MdxFrontmatter":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Users/alex/git/ib/code-notes/node_modules/gatsby-theme-code-notes/src/templates/Note.js
```

Therefore I'm requesting that the requirement of specifying these front matter keys is dropped. Not every note needs a link, or an emoji.

Thanks!

**Comment by mrmartineau** [comment]
hey @IronicBadger, thanks for raising the issue. I will update the GraphQL types to ensure that these items can be optional.

**Comment by mrmartineau** [comment]
@IronicBadger I believe I have fixed this now so please ensure you update after the next version of the theme is published.

**Comment by mrmartineau** [comment]
@IronicBadger  [v1.7.2](https://github.com/mrmartineau/gatsby-theme-code-notes/releases/tag/v1.7.2) has been released now. Please can you update and let me know if this bug is still there?

**Comment by IronicBadger** [comment]
Yup! No emoji specified and now all notes default to the notepad emoji. Great turn around time!

Is it possible to hide emoji altogether? Thanks!
