### ISSUE TITLE
Error on hot reload after editing gatsby-config.js

### ISSUE THREAD

**Issue by AlexEyler** [mrmartineau/gatsby-theme-code-notes#16]
Hey man,

Love this theme.

Ran into an issue on hot reload after editing the gatsby-config.js file and changing a setting (set `showThemeInfo` to true, though it seems to happen on any change, like editing the description):

```
 ERROR #85925  GRAPHQL

There was an error in your GraphQL query:

Cannot return null for non-nullable field SiteSiteMetadata.gitRepoContentPath.

The field "SiteSiteMetadata.gitRepoContentPath." was explicitly defined as non-nullable via the schema customization API (by yourself or a plugin/theme). This means that this field is not optional and you have to define a value. If this is not your desired behavior and you defined the schema yourself, go to "createTypes" in gatsby-node.js. If you're using a plugin/theme, you can learn more here on how to fix field types:
https://www.gatsbyjs.org/docs/schema-customization/#fixing-field-types

   1 | query usersalexeylerDevelopmentwebmyNotesnodeModulesgatsbyThemeCodeNotessrcuseSiteMetadataTs1322576299 {
   2 |   site {
   3 |     siteMetadata {
   4 |       title
   5 |       description
>  6 |       gitRepoContentPath
     |       ^
   7 |       showThemeInfo
   8 |       showDescriptionInSidebar
   9 |       logo
  10 |     }
  11 |   }
  12 | }
  13 |

File path: /Users/alexeyler/Development/web/my-notes/node_modules/gatsby-theme-code-notes/src/use-site-metadata.ts
Plugin: none
```

When reloading the web page, I see this error:
```
TypeError: Cannot read property 'gitRepoContentPath' of null
NotePage
node_modules/gatsby-theme-code-notes/src/components/NotePage/NotePage.tsx:46
  43 |   data,
  44 |   pageContext,
  45 |   location,
> 46 | }) => {
  47 |   if (!data) {
  48 |     return null
  49 |   }
```

I'm a backend developer by trade (first time using react, gatsby, etc.), but I can take a swing and see if I can find the root cause.

**Comment by AlexEyler** [comment]
Found this error when looking at the GraphQL results after a hot reload (before a hot reload I can see the correct git repo path):

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field SiteSiteMetadata.gitRepoContentPath.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "site",
        "siteMetadata",
        "gitRepoContentPath"
      ],
      "stack": [
        "Error: Cannot return null for non-nullable field SiteSiteMetadata.gitRepoContentPath.",
        "    at completeValue (/Users/alexeyler/Development/web/gatsby-theme-code-notes/node_modules/graphql/execution/execute.js:560:13)",
        "    at /Users/alexeyler/Development/web/gatsby-theme-code-notes/node_modules/graphql/execution/execute.js:492:16",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
      ]
    }
  ],
  "data": {
    "site": {
      "siteMetadata": null
    }
  }
}
```

**Comment by mrmartineau** [comment]
Hey @AlexEyler thanks for giving the theme a go, I am sorry you are experiencing issues. Unless I am mistaken, I think that there was a recent Gatsby update that triggers a hot-reload when the `gatsby-config.js` file gets updated. This might partly explain the issue you're facing.

I [recently updated](https://github.com/mrmartineau/gatsby-theme-code-notes/commit/855ea5357619dbec691fbb1b3afd0f91dafed3bc) the GraphQL types for `SiteSiteMetadata` to ensure that those values are non-nullable. Default values are set in the theme so they should never be `null` which makes this bug all the more confusing.

I will investigate this and get back to you.

**Comment by mrmartineau** [comment]
Hi @AlexEyler I believe I have fixed this now so please ensure you update after the next version of the theme is published.

**Comment by mrmartineau** [comment]
@AlexEyler [v1.7.2](https://github.com/mrmartineau/gatsby-theme-code-notes/releases/tag/v1.7.2) has been released now. Please can you update and let me know if this bug is still there?

**Comment by AlexEyler** [comment]
@mrmartineau the error goes away, but updating the description causes the description to disappear from the website now. Not a big deal (I doubt these fields are changing often anyway)!

**Comment by mrmartineau** [comment]
@AlexEyler thanks for confirming it. I think this is an issue with Gatsby itself to be honest. Agreed that those fields do not change much. I will see if there's an upstream issue that relates to this.
