### ISSUE TITLE
wordwrap on code blocks

### ISSUE THREAD

**Issue by IronicBadger** [mrmartineau/gatsby-theme-code-notes#17]
It'd be great to be able to stop code blocks for some longer commands from going off the side of the screen using wordwrap. Is this possible? 

Example:

https://openshift.ktz.cloud/etcd-member-table

**Comment by mrmartineau** [comment]
@IronicBadger it probably is possible using something like Prettier (there's [a Gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-remark-prettier) that may do this), but that would mean my theme is enforcing a coding style on everyone's notes, which I don't think is a good idea.

You could use a Prettier IDE plugin with your own config to do this for yourself perhaps. Could you give that a try and let me know how you go?
