### ISSUE TITLE
Sub folders in notes

### ISSUE THREAD

**Issue by bluee** [mrmartineau/gatsby-theme-code-notes#22]
If you try and structure your notes in sub-folders then links are incorrect.

eg. 
notes/react/topic1.md will be linked ass notes/topic1. Navigating directly to /react/topic1 still works.

**Comment by mrmartineau** [comment]
Hi @bluee, I must admit I haven't tried putting notes into subfolders. Let me see what I can do to enable this without breaking the existing functionality.

**Comment by mrmartineau** [comment]
@bluee this was a fairly simple fix and oversight on my part to be honest. Please update to version [1.8.0](https://github.com/mrmartineau/gatsby-theme-code-notes/releases/tag/v1.8.0) to get your notes in subfolders.

**Comment by bluee** [comment]
Thanks @mrmartineau
