### ISSUE TITLE
Can you insert images?

### ISSUE THREAD

**Issue by IronicBadger** [mrmartineau/gatsby-theme-code-notes#24]
Thanks for the work on this theme, it's really excellent and I'm enjoying it so far.

I tried two ways to insert an image into a note but neither worked. Any tips?

```
![image](images/image.png)

<img src=images/image.png>
```

The markdown down syntax results in a 404. How are the paths rendered? I tried a few permutations but didn't find the right one yet.

![image](https://user-images.githubusercontent.com/2773080/84797923-586bc800-afc8-11ea-9422-e63a11e9a8bc.png)

The HTML version just straight up causes gatsby to not compile.

For completeness, here is the file layout.

![image](https://user-images.githubusercontent.com/2773080/84798167-a2ed4480-afc8-11ea-864f-abc1dde82cbf.png)

**Comment by mrmartineau** [comment]
hey @IronicBadger, I have just published v1.9.0 which adds support for images. Let me know how you get on.

**Comment by IronicBadger** [comment]
Wow! That was fast. Thanks again. Works great.
