### ISSUE TITLE
Set image max-width

### ISSUE THREAD

**Issue by pollmix** [mrmartineau/gatsby-theme-code-notes#39]
Now images are overflowing. Can you please set the width on image `max-width: 100%`

**Comment by mrmartineau** [comment]
@pollmix can you send me an example link where you're getting this issue?

**Comment by mrmartineau** [comment]
@pollmix, I just fixed this in [v1.15.1](https://github.com/mrmartineau/gatsby-theme-code-notes/releases/tag/v1.15.1)

**Comment by pollmix** [comment]
Great!! thanks
