### ISSUE TITLE
Tags are hidden under the theme selector

### ISSUE THREAD

**Issue by e-minguez** [mrmartineau/gatsby-theme-code-notes#46]
Sites such as https://notes.apiscp.com/ or https://openshift.ktz.cloud/ where you need to scroll the tag list doesn't allow you to select the latest ones as the theme selector overlays them.
![image](https://user-images.githubusercontent.com/346758/90110867-266bad80-dd4e-11ea-9e5c-8ad26265f742.png)

**Comment by IronicBadger** [comment]
I just came here to open this bug! Nice one.

**Comment by mrmartineau** [comment]
Can you let me know which browsers this affects? For me at least, on Chrome it works fine but not on Firefox. Are you on Windows or OSX? 

I don't have much time to make this fix so would one of you be able to tackle it?

**Comment by e-minguez** [comment]
It happens to me on Fedora 32 both with Firefox (79.0) and Chrome (84.0.4147.125)

**Comment by mrmartineau** [comment]
hey guys, I just fixed this in [v1.15.1](https://github.com/mrmartineau/gatsby-theme-code-notes/releases/tag/v1.15.1)
