### ISSUE TITLE
Automatically select light/dark mode based off user preference

### ISSUE THREAD

**Issue by timrossback** [mrmartineau/gatsby-theme-code-notes#48]
Hey,

Since this theme appears to come out-of-the-box with both a light and dark mode, what about adding some sort of automatic theme selector based on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)? From my experience, all you need is `@media (prefers-color-scheme: dark) { ... }` to automatically select this. I don't know how that'll interact with the theme toggler though.

**Comment by mrmartineau** [comment]
Hey @timrossback, thanks for raising the issue. This functionality is extremely easy to add since this theme already uses Theme UI for this. 

I don't have much time to make this fix so would you be able to tackle it?

**Comment by timrossback** [comment]
I'd be happy to maybe give it a crack @mrmartineau, but I'm really not too familiar with Gatsby or React. I'll see what I can do though.

**Comment by mrmartineau** [comment]
It should only be a one line change in the `index.js` file within the `gatsby-plugin-theme-ui` directory. See here for the docs: https://theme-ui.com/color-modes#initialize-mode-with-prefers-color-scheme-media-query

**Comment by timrossback** [comment]
Yeah, I have absolutely no idea how to do this 😆 Sorry! I was looking through the `index.js` file, and I just simply don't know enough about how this theme and Theme-UI works hahahaha.

From my abstraction, I think `useColorSchemeMediaQuery: true,` just needs to be added before [the `export default colours` line](https://github.com/mrmartineau/gatsby-theme-code-notes/blob/master/gatsby-theme-code-notes/src/gatsby-plugin-theme-ui/index.js#L25) or possibly at the very end for maintainability, but since I'm unable to test it locally (good ole' Windows), I really wouldn't feel confident putting forward a PR. Sorry! 

Might be one for someone else who is more active with JavaScript, Gatsby and Reach to grab.

**Comment by mrmartineau** [comment]
Hey @timrossback, that is exactly how I'd do it as well. No worries, I'll see if I can make this change over the next few days.

**Comment by mrmartineau** [comment]
@timrossback I have done this now and it will ready in the next release.

**Comment by timrossback** [comment]
Great, thank you so much, and I'm so sorry I couldn't be more help!
