### ISSUE TITLE
Fresh install doesn't build

### ISSUE THREAD

**Issue by RealOrangeOne** [mrmartineau/gatsby-theme-code-notes#65]
It looks like the lock files are hiding some requirements for the package, such that installing without the `yarn.lock` (in an attempt to use the standard `package-lock.json`) doesn't work.

## Steps to reproduce:

- Clone https://github.com/MrMartineau/gatsby-starter-code-notes
- `npm install`
- `npm run build` fails

If installed via yarn (replacing `npm install` with `yarn install`), it works as expected.

## Errors

```
failed Building static HTML for pages - 3.641s

 ERROR #95313

Building static HTML failed for path "/example-note/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  11 |   const theme = preset.default || preset
  12 |
> 13 |   const themeWithPrism = merge(theme, {
     |                                ^
  14 |     styles: {
  15 |       pre: prismPreset,
  16 |     },


  WebpackError: TypeError: Object(...) is not a function

  - provider.js:13
    node_modules/gatsby-plugin-theme-ui/src/provider.js:13:32
```

I've had a number of errors, but this seems to be the main one. It's hard to track down exactly which it would be

**Comment by RealOrangeOne** [comment]
Interestingly, it seems the way to fix this is to pin `"theme-ui": "^0.3.1"`. This is done in the example in the repo, but not in the starter.

The version matches what's in the requirements, so exactly why this is needed I don't know!

**Comment by RealOrangeOne** [comment]
I stand corrected, this doesn't actually fix it correctly.

Whilst it does allow the site to be built correctly, features such as syntax highlight are missing.

@mrmartineau would be great to get this fixed ASAP, as it makes the theme functionally unusable unless you have an existing lockfile

**Comment by mrmartineau** [comment]
@RealOrangeOne this issue is precisely why there is a lockfile. Please use yarn to install package dependencies because I cannot maintain both.

**Comment by RealOrangeOne** [comment]
lockfiles are only really designed for the final application, rather than libraries. When using `npm install` to install this package, it's broken, which is an issue.

For the starter project, I agree that works as expected, as there's a lockfile already there. However if I wanted to build from scratch myself without the starter, a valid path, the project will not run.

**Comment by mrmartineau** [comment]
Sorry, I disagree. Lockfiles are used for libraries and dependencies as well, otherwise there would be no guarantee that the dependencies match. I understand your frustration because yarn has been used but I won't be changing it for just your use-case.
