### ISSUE TITLE
After basePath is set, the note's path will not automatically add the value of basePath?

### ISSUE THREAD

**Issue by ZionDoki** [mrmartineau/gatsby-theme-code-notes#80]
Here is my config of `basePath`.

```javascript
module.exports = {
  siteMetadata: {
    ...
  },
  plugins: [
    {
      resolve: 'gatsby-theme-code-notes',
      options: {
        contentPath: 'notes',
        basePath: '/notes/',
        showThemeInfo: false,
        showDescriptionInSidebar: true,
        logo: ''
      },
    },
  ],
}
```

When I set `basePath` to `/notes/`, It's works and totally fine, but when I click the note whose URL is `todo`. It doesn't link to `/notes/todo` but `todo`. 

I really don't know is this a bug or just my mistake of using. I'm totally rookie in gatsby.

and the other question is how can I get  `basePath` settings through `graphql`, I couldn't find a way :(

Looking forward to your reply！plz..

**Comment by ZionDoki** [comment]
Fine, I solve the problem by a simple and crude methods that is add data manually to `GraphQL`.

Thank you for your work still :)

```javasript
// path: ./gatsby-node.js

const config = require('./gatsby-config')

exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
  config.plugins.forEach(plugin => {
    const node = {
      name: plugin.resolve,
      options: plugin.options,
      id:createNodeId(`Plugin-${plugin.name}`),
      internal: {
        type: "Plugin",
        contentDigest: createContentDigest(plugin),
      },
    }
    actions.createNode(node)
  })
}
```
I'm still figuring out how to pass `basePath` to `NoteListItem's slug` the way that project have

**Comment by mrmartineau** [comment]
hi @ZionDoki, thanks for raising this. I am working on this now and the next release will include the fix

**Comment by johnchristopher** [comment]
I have a question. Why can't the static files being rendered be used in any arbitrary folders by using relative paths for CSS and JavaScript files ?
