### ISSUE TITLE
Add search results page

### ISSUE THREAD

**Issue by mrmartineau** [mrmartineau/gatsby-theme-code-notes#9]
e.g. `/search?query=prop`

This page could be reached when a user hits [enter] while searching

- Create page that is based on the query param
- When user hits [enter] on a search, come to this page
- Add [opensearch](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md#overview) so that the site can be searched from the browser

**Comment by khalido** [comment]
Could this just open the main page with the search bar prefilled with the query? So no need for a seperate search page.

And looking forward to opensearch integration!

**Comment by mrmartineau** [comment]
This feature was added in v1.10.0
